apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-welcome-php
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/welcome-php/overlays/syncwaves-and-hooks/
    repoURL: https://github.com/rh-mobb/gitops-bgd-app
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sync:
    comparedTo:
      destination:
        namespace: openshift-gitops
        server: https://kubernetes.default.svc
      source:
        path: apps/welcome-php/overlays/syncwaves-and-hooks/
        repoURL: https://github.com/rh-mobb/gitops-bgd-app
        targetRevision: main
